In [1]:
import pandas as pd
import numpy as np

np.random.seed(1)

rows = 300

data = {
    "Order ID": [f"ORD-{1000+i}" for i in range(rows)],
    "Order Date": pd.date_range(start="2019-01-01", periods=rows, freq="D"),
    "Customer Name": np.random.choice(
        ["Arun", "Meena", "Ravi", "Anita", "Rahul", "Priya", "Kiran", "Sneha"], rows
    ),
    "Region": np.random.choice(
        ["North", "South", "East", "West"], rows
    ),
    "Category": np.random.choice(
        ["Furniture", "Technology", "Office Supplies"], rows
    ),
    "Sales": np.random.choice([None, 1200, 2500, 3700, 4800, 6200], rows),
    "Profit": np.random.randint(-1000, 3000, rows)
}

df = pd.DataFrame(data)

# Add duplicate rows intentionally
df = pd.concat([df, df.iloc[:20]], ignore_index=True)

# Save to Excel
df.to_excel("Large_Sales_Dataset.xlsx", index=False)

df.head()

   Order ID Order Date Customer Name Region         Category Sales  Profit
0  ORD-1000 2019-01-01         Priya  North        Furniture  None    1057
1  ORD-1001 2019-01-02         Anita  South        Furniture  None     127
2  ORD-1002 2019-01-03         Rahul   East  Office Supplies  None     158
3  ORD-1003 2019-01-04          Arun  North  Office Supplies  2500    2742
4  ORD-1004 2019-01-05         Sneha  North        Furniture  None    2907

In [2]:
import pandas as pd
df = pd.read_excel("Large_Sales_Dataset.xlsx")

In [4]:
df.head()

   Order ID Order Date Customer Name Region         Category   Sales  Profit
0  ORD-1000 2019-01-01         Priya  North        Furniture     NaN    1057
1  ORD-1001 2019-01-02         Anita  South        Furniture     NaN     127
2  ORD-1002 2019-01-03         Rahul   East  Office Supplies     NaN     158
3  ORD-1003 2019-01-04          Arun  North  Office Supplies  2500.0    2742
4  ORD-1004 2019-01-05         Sneha  North        Furniture     NaN    2907

In [6]:
df.head()
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       320 non-null    object
 1   Order Date     320 non-null    datetime64[ns]
 2   Customer Name  320 non-null    object
 3   Region         320 non-null    object
 4   Category       320 non-null    object
 5   Sales          270 non-null    float64
 6   Profit         320 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 17.6+ KB

In [8]:
df.isnull().sum()

Order ID          0
Order Date        0
Customer Name     0
Region            0
Category          0
Sales            50
Profit            0
dtype: int64

In [11]:
df=df.dropna()

In [12]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df.to_excel("Cleaned_Large_Sales_Dataset.xlsx", index=False)